LIST = {
    "'COPASTETIC'": "1 -Street slang for everythings good, ok, chill. A favorite of Master Deputy Mark Laureano.",
    "'PORN' AGAIN": "2 -Usually involves Trooper Casey. Stops are usually made when citizen is leaving a porn store. Almost always leads to embarrassment.",
    "ACCIDENT": "3 - A vehicle, motorcycle, bicycle that strikes or collides another vehicle, a stationary object, a pedestrian, or an animal.",
    "ACTIN' A FOOL": "4 - Lacking or exhibiting a lack of good sense or judgment.",
    "ALCOHOL": "5 - Any fermented liquor, such as wine, beer, or distilled spirit, that contains ethyl alcohol, or ethanol.",
    "AMBULANCE": "6 - A vehicle specially equipped for taking sick or injured people to and from the hospital, especially in emergencies.",
    "AMMUNITION": "7 - A supply or quantity of bullets and shells.",
    "ANKLE BRACELET": "8 - An ankle monitor (also known as a tether, or ankle bracelet) is a homing device that defendants under house arrest or parole are required to wear. At all times, the ankle monitor sends a radio frequency signal containing location and other information to a receiver.",
    "ARMED ROBBERY": "9 - A robbery in which the robber is armed with a dangerous weapon.",
    "ARRESTED": "10 - Seize (someone) by legal authority and take into custody.",
    "ASSAULT": "11 - An assault is carried out by a threat of bodily harm coupled with an apparent, present ability to cause the harm.",
    "ASSAULT RIFLE": "12 - A selective-fire rifle that uses an intermediate cartridge and a detachable magazine.",
    "BAREFOOT": "13 - Not wearing shoes. Usually in severe need of pedicure.",
    "BARKING DOG": "14 - When a canine (other than police K9) barks or whines.",
    "BEER": "15 - An aluminium can, bottle, keg, or cup/container containing beer.",
    "BEER GUT": "16 - Abdominal obesity. Excess weight that develops over time around the center of the body. Also known as a pot belly.",
    "BICYCLE": "17 - A vehicle composed of two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars attached to the front wheel.",
    "BLOOD": "18 - The bodily fluid that circulates in the heart, arteries, capillaries, and veins of a vertebrate animal carrying nourishment and oxygen to and bringing away waste products from all parts of the body.",
    "BLUE DOOR MOTEL": "19 - The Palmetto Inn in Columbia, SC.",
    "BLUNT": "20 - Hollowed-out cigar filled with marijuana.",
    "BODILY FLUIDS": "21 - Liquids originating from inside the bodies of living people. (Blood, Feces, Breast Milk, Semen, Saliva, Urine, Vomit, etc.)",
    "BRASS KNUCKLES": "22 - Pieces of metal shaped to fit around the knuckles. Despite their name, they are often made from other metals, plastics or carbon fibers.",
    "BREATHALYZER": "23 - A device used by police for measuring the amount of alcohol in a driver's breath.",
    "BRICK O' WEED": "24 - A pound (or more) of marijuana that is compacted into a cube, thus resembling a brick. This is a process that is usually done for the purpose of shipping and/or smuggling the substance.",
    "BROKEN HEADLIGHT": "25 - A non-functioning light at the front of a motor vehicle or motorcycle.",
    "BROKEN TAILLIGHT": "26 - A non-functioning red light at the rear of a motor vehicle, motorcycle, or bicycle.",
    "BURGLARY": "27 - Entry into a building illegally with intent to commit a crime, especially theft.",
    "CSI": "28 - Crime Scene Investigation. Forensic science technician that collects, identifies, classifies, and analyzes physical evidence related to criminal investigations.",
    "CAMOUFLAGE": "29 - The disguising of military personnel, equipment, and installations by painting or covering them to make them blend in with their surroundings.",
    "CAR CHASE": "30 - Vehicular hot pursuit of suspects by law enforcers.",
    "CAR SEAT": "31 - A portable seat for an infant or a small child that attaches to an automobile seat and holds the child safely.",
    "CHILD NEGLECT": "32 - Child neglect is a form of child abuse, and is a deficit in meeting a child's basic needs, including the failure to provide adequate health care, supervision, clothing, nutrition, housing as well as their physical, emotional, social, educational and safety needs.",
    "CIGARETTE": "33 - A person smoking a lit cigarette.",
    "CLENCHED BUTTOCKS": "34 - Making one tighten the buttocks through extreme fear or embarrassment.",
    "COCAINE": "35 - An addictive drug derived from coca or prepared synthetically, used as an illegal stimulant and sometimes medicinally as a local anesthetic.",
    "CONSTTIUTIONALIST": "36 - Individuals who believe the idea, often associated with the political theories of John Locke and the founders of the American republic, that government can and should be legally limited in its powers, and that its authority or legitimacy depends on its observing these limitations.",
    "CONVICT": "37 - A person who has committed a felony is a felon, and upon conviction of a felony in a court of law a person is known as a convicted felon or a convict.",
    "COP TAKE DOWN": "38 - An act of bringing one's opponent to the ground.",
    "COUGH SYRUP": "39 - DXM or liquid medicine to either to suppress or expectorate a cough, or to get intoxicated.",
    "CROWN ROYAL BAG": "40 - Placing illegal items inside a Crown Royal (Canadian Whisky) bag.",
    "CRYING": "41 - Shedding of tears (or welling of tears in the eyes) in response to an emotional state.",
    "CYCLING DIRTY": "42 - Riding a bicycle while drunk or high. Known to ride in middle of the street with broken/no light.",
    "DUI CHECKPOINT": "43 - Sobriety checkpoints are police stops, or checkpoints, where officers are set up on a roadway to randomly stop vehicles to check for impaired drivers. These are usually set up during times when impaired driving is known to happen, such as holiday weekends.",
    "DUI TEST": "44 - Standardized Field Sobriety Test (SFST) is a battery of 3 tests performed during a traffic stop in order to determine if a driver is impaired. The 3 tests that make up the SFST are the horizontal gaze nystagmus (HGN), the walk-and-turn, and the one-leg stand tests.",
    "DAISY DUKES": "45 - Shorts shorts. Usually includes one or more of the following: exposed butt cheeks, generous muffin top, severe wedgie, picking of said wedgie or cellulite.",
    "DAN ABRAMS IS 'PUN'NY": "46 - Puns made by LivePD host Dan Abrams.",
    "DESTROYING EVIDENCE": "47 - Getting rid/destroying of items that may incriminate.",
    "DETAINED": "48 - To hold or keep in or as if in custody.",
    "DOG BITE": "49 - When a dog takes his teeth and latches onto and penetrating a person's skin.",
    "DOMESTIC ANIMAL": "50 - Any of various animals that have been tamed and made fit for a human environment. (Dogs, Cats, Hamsters, etc.)",
    "DOMESTIC DISTURBANCE": "51 - A dispute requiring police response that involves two or more people engaged in an intimate relationship (married or divorced couples, live-in lovers, people on a first date, problems between adults and children, or adults and elderly parents).",
    "DON'T FILM ME": "52 - When someone doesn't want to be filmed by the Live PD crew.",
    "DRUG BUST": "53 - When law enforcement seizes large quantities of drugs.",
    "DRUG PARAPHERNALIA": "54 - Any equipment, product, accessory, or material that is modified for making, using, or concealing drugs, typically for recreational purposes.",
    "DRUGS TOSSED": "55 - Where drugs are tossed or thrown by a person.",
    "DRUNK WALKING": "56 - Walking around under heavy influence of alcohol.",
    "EXPIRED LICENSE": "57 - Out of date Driver's License.",
    "EXPIRED TAGS": "58 - Out of date tags/stickers on vehicle tag/licence plate.",
    "FAKE ID": "59 - Federal or State identification that is not real.",
    "FARM ANIMAL": "60 - Any domestic species of cattle, sheep, swine, goats, llamas, or horses.",
    "FIGHT": "61 - Take part in a violent struggle involving the exchange of physical blows or the use of weapons.",
    "FIRE": "62 - Combustion or burning, in which substances combine chemically with oxygen from the air and typically give out bright light, heat, and smoke.",
    "FIST BUMP": "63 - A fist bump (or power five,) is a gesture similar in meaning to a handshake or high five. A fist bump can also be a symbol of giving respect or approval. It can be followed by various other hand and body gestures and may be part of a dap greeting.",
    "FIVE FINGER DISCOUNT": "64 - Theft or pilferage, typically of a small item; shoplifting.",
    "FOOT CHASE": "65 - Pursue on foot in order to catch or catch up with.",
    "FREQUENT-FLYER": "66 - Individual who has been arrested multiple times by police or a location/individual that is frequently visited by police.",
    "FULL MOON": "67 - The phase of the moon in which its whole disk is illuminated or a 'naked butt'.",
    "GANG BANGER": "68 - A member of a gang.",
    "GANG UNIT": "69 - A specialized unit with at least two officers primarily assigned to handle matters related to youth gangs.",
    "GIFTIE": "70 - The name for K-9 Flex's toy ball.",
    "GOOBER GRAZING": "71 - When being searched and the officer comes in contact with suspects genitals.",
    "GOOD SAMARITAN": "72 - A charitable or helpful person.",
    "GRILLING": "73 - Cook (something) using a bbq grill.",
    "GUN FOUND": "74 - A handgun, rifle, or shotgun found in vehicle or on a person or in belongings.",
    "GUN SHOW": "75 - Large muscular arms, or an actual gun show.",
    "HANDCUFFED": "76 - Put handcuffs on (someone).",
    "HANDGUN": "77 - A gun designed for use by one hand, especially a pistol or revolver.",
    "HANDSHAKE": "78 - An act of shaking a person's hand with one's own.",
    "HELICOPTER": "79 - An aircraft capable of hover, vertical flight, and horizontal flight in any direction.",
    "HIT & RUN": "80 - The crime of a driver of a vehicle who is involved in a collision with another vehicle, property or human being, who knowingly fails to stop to give his/her name, license number, and other information as required by statute to the injured party, a witness, or law enforcement officers.",
    "HOGTIED": "81 - Secure by fastening together the hands and feet (of a person) or all four feet (of an animal).",
    "HOOKER": "82 - Slang term for a prostitute or someone who exchanges sex for money. (Ho, lady of the night, workin' girl)",
    "HOOPTY": "83 - A large older automobile, often in poor condition; jalopy.",
    "JAWS OF LIFE": "84 - A hydraulic apparatus used to pry apart the wreckage of crashed vehicles in order to free people trapped inside.",
    "K9 USED": "85 - A dog trained to aid the police, as in tracking criminals or detecting controlled substances.",
    "KITTY CAT": "86 - A small domesticated carnivorous mammal with soft fur, a short snout, and retractile claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.",
    "KNIFE": "87 - An instrument composed of a blade fixed into a handle, used for cutting or as a weapon.",
    "LATEX GLOVES": "88 - Are natural material, made out of rubber. They are a popular choice of protective glove for medical, industrial, or law enforcement use. The primary reason people would choose an alternative to latex is because many people suffer from latex allergies.",
    "LIAR, LIAR": "89 - When someone lies to a law enforcement officer.",
    "LIGHTS OFF": "90 - Operating a vehicle on a public highway during the period from one-half hour after sunset to one-half hour before sunrise or at any other time when windshield wipers are in use, as a result of rain, sleet, snow, hail or other unfavorable atmospheric condition, and at such other times as visibility for a distance of one thousand feet ahead of such motor vehicle is not clear, lighted head lamps turned on.",
    "LITTERING": "91 - A person, from a vehicle or otherwise, that dumps, throws, drops, deposit,s discards, or otherwise disposes of litter or other solid waste upon public or private property or waters including, but not limited to, a highway, park, beach, campground, forest land, recreational area, trailer park, road, street, or alley.",
    "LIVEPD NATLIE": "92 - Natlie, from Live PD control room.",
    "LIVEPD SHOUTOUT": "93 - A message of congratulation, support, or appreciation for Live PD.",
    "LIVEPD IS FOR LOVERS": "94 - When someone professes their love for another person or acts a fool for love on LivePD.",
    "MAN BUN": "95 - The man bun is a ridiculous masculine twist on the female variation of the hairstyle. Favorite of Hipsters and douche bags.",
    "METH": "96 - The drug methamphetamine.",
    "METH PIPE": "97 - A hollow glass bulb, with an extruding shaft, used for vaporizing methamphetamine or crystal meth, in order to inhale the vapor for its stimulating properties.",
    "MOOBS": "98 - A combination of the words 'man' and 'boobs.' This is what happens when fat gathers in a male's chest area, and gives him the appearance of having breasts. Usually seen in overweight males, but can strangely also occur in men who are not really overweight.",
    "MOTORCYCLE CHASE": "99 - Motorcycle hot pursuit of suspects by law enforcers.",
    "MOUTH SALAD": "100 - The act in which a person consumes marijuana in order to hide from law enforcement officers.",
    "NARCAN": "101 - narcan (nar-kan) noun: Brand name of the medical drug Naloxone, which serves as an antidote to opiod overdose.",
    "NEEDLE": "102 - An instrument (as for the injection of medicine or the withdrawal of bodily fluids) that consists of a hollow barrel fitted with a plunger and a hollow needle.",
    "NIGHT VISION": "103 - Ability to see in low light conditions with a video camera or goggles.",
    "NO HEADLIGHTS": "104 - When the lights at the front of a motor vehicle or motorcycle are not turned on.",
    "NO ID": "105 - Is not in possession of a Driver's Licence or a legal form of identification.",
    "NO INSURANCE": "106 - Does not have auto insurance for the car they are driving.",
    "NO PANTS": "107 - Someone isn't wearing pants or shorts.",
    "NO SEAT BELT": "108 - Operating a vehicle on a public highway without waring three-point seat belt.",
    "NO SHOES": "109 - Not wearing covering for the feet.",
    "NOISE COMPLAINT": "110 - No person, business establishment or organization shall recklessly make or cause to be made or continued, allow, or participate in the making or causing to be made or continued, any loud or unusual noise that disturbs the peace.",
    "NOT MY...": "111 - Someone claims that something isn't theirs. (Not my car, not my pants, not my shoes, not my drugs, etc.)",
    "OBAMA MART": "112 - Obama Gas Station in Columbia, SC frequently seen on Live PD.",
    "OPEN CONTAINER": "113 - Refers to having any opened alcoholic beverage in an openly public places such as sidewalks, parks and vehicles.",
    "OUT OF STATE LICENSE": "114 - Possesses a Driver's License from another state.",
    "PCP": "115 - Slang for the drug phencyclidine. Also known as angeldust. Probably the scariest of all drugs. Was used as a horse tranquilizer. Makes the user hallucinate, become extremely violent, and not feel anything. People have been known to do horrible things to themselves while under the influence of PCP.",
    "PILLS": "116 - Small round mass of solid medicine to be swallowed whole.",
    "PINK HANDCUFFS": "117 - Deputy Rebecca Loeb of Lake County, IL, has fancy pink handcuffs.",
    "PRISON PURSE": "118 - A body cavity used to store valuables such as money, drugs or weapons. Popular in a prison setting. Usually happens during traffic stops involving Sgt. Denver Leverett and K-9 Flex. Suspects are known to hide illegal drugs in their rectums to prevent detection. After some crafty questioning the suspect usually confesses to the possession of the illegal items and or crimes.",
    "PROBATION": "119 - The release of an offender from detention, subject to a period of good behavior under supervision. Usually with conditions.",
    "RESISTING ARREST": "120 - The act of physically struggling against, or attempting to elude a police officer, in order to escape being restrained.",
    "RESTRICTED LICENSE": "121 - Allow the holder to drive for specific purposes. These might include driving to and from work or school, to seek medical treatment or to go to a grocery store.",
    "RIDIN' DIRTY": "122 - Driving with a illegal weapon or drugs. First coined by Houston Rap group U.G.K.(Bun B and Pimp C) In a song 'ridin dirty'.",
    "RIDIN' DIRTY TRIFECTA": "123 - Driving while having three of the following: illegal weapon, drugs, under the influence, warrants, suspended licence, stolen car or motorcycle, etc.",
    "RIGHTS READ": "124 - Miranda rights, is a right to silence warning given by police in the United States to criminal suspects in police custody (or in a custodial interrogation) before they are interrogated to preserve the admissibility of their statements against them in criminal proceedings. (SEE 'MIRANDA RIGHTS')",
    "ROAD RAGE": "125 - Aggressive or angry behavior exhibited by a driver of a road vehicle, which includes rude gestures, verbal insults, physical threats or dangerous driving methods targeted toward another driver in an effort to intimidate or release frustration.",
    "SWAT": "126 - Special Weapons and Tactics: a military-like unit within the US police force, trained to deal with specially dangerous situations, such as hostage-taking and riots.",
    "SAGGING PANTS": "127 - Is a manner of wearing trousers or jeans which sag so that the top of the trousers or jeans are significantly below the waist, sometimes revealing much of the underwear.",
    "SCALES": "128 - An instrument or machine used for weighing things like illegal drugs.",
    "SEARCH": "129 - Try to find something by looking or otherwise seeking carefully and thoroughly.",
    "SELFIE": "130 - A photograph that one has taken of oneself, typically one taken with a smartphone or webcam and shared via social media.",
    "SEX IN CAR": "131 - Sexual activity, including sexual intercourse or other act performed with another for sexual gratification, in a vehicle.",
    "SEX OFFENDER": "132 - A person who has committed a sex crime.",
    "SEX TOY": "133 - An object or device used for sexual stimulation or to enhance sexual pleasure.",
    "SHOTGUN": "134 - A smooth bore gun for firing small shot at short range.",
    "SHOTS FIRED": "135 - A handgun, rifle, or shotgun discharged.",
    "SNAKE": "136 - A long limbless reptile that has no eyelids, a short tail, and jaws that are capable of considerable extension. Some snakes have a venomous bite.",
    "SOCKS 'N SLIDES": "137 - Someone wearing sandals with socks.",
    "SPIKE STRIP": "138 - Is a device used to impede or stop the movement of wheeled vehicles by puncturing their tires.",
    "SPIT HOOD": "139 - Spit hoods (also known as “spit masks”) have been increasingly used by police and other law enforcement officers in recent years. A spit hood, or spit mask, is a fabric covering or 'hood' that can be placed over a person's head and secured at the neck with an elastic band.",
    "SPITTING": "140 - Eject saliva forcibly from one's mouth, sometimes as a gesture of contempt or anger.",
    "SPOON": "141 - Spoons, bottle caps, or other containers used to dissolve drugs.",
    "STICKS": "142 - Sgt. Sean 'Sticks' Larkin with the Gang Unit of the Tulsa Police Department.",
    "STOLEN CAR": "143 - Motor vehicle theft or grand theft auto is the criminal act of stealing or attempting to steal any motor vehicle, usually an automobile.",
    "STOLEN TAGS": "144 - Tags removed from one vehicle to use on another. Usually found on a stolen car.",
    "SUSPENDED LICENSE": "145 - Administrative License Revocation or ALR is when a driver's license is taken away by law enforcement at the time of the offense or stop by police upon the failure or refusal of a chemical test.",
    "SUSPICIOUS VEHICLE": "146 - A vehicle that is engaged in unusual or out of the ordinary behaviour.",
    "TAG LIGHT": "147 - A light that illuminates license plate/tag.",
    "TASER": "148 - Conducted electrical weapon (CEW) is an electroshock weapon that fires two small dart-like electrodes, which stay connected to the main unit by conductors, to deliver electric current to disrupt voluntary control of muscles causing 'neuromuscular incapacitation'.",
    "TATTOOS": "149 - A person with visible tattoos.",
    "TEAM RCSD": "150 - Any member of Richland County Sheriff’s Department.",
    "THANK YOU": "151 - When someone thanks an officer.",
    "TINT VIOLATION": "152 - Window tint being too dark.",
    "TOOTERS": "153 - Straws for snorting Cocaine or Heroin.",
    "TOUCH TAIL LIGHT": "154 - Police officers touch the tail light of the vehicles in order to leave their fingerprints on it.",
    "TRAFFIC STOP": "155 - Being pulled over, is a temporary detention of a driver of a vehicle by police to investigate a possible crime or minor violation of law.",
    "TRESPASSING": "156 - A wrongful entry upon the lands of another.",
    "TWEAKER": "157 - Slang term for someone exhibiting compulsive or repetitive behaviour due to the use of stimulants, most commonly methamphetamine.",
    "UNDERAGE DRINKING": "158 - The consumption of alcohol under a legally specified age, usually before one's 21st birthday.",
    "WAD OF CASH": "159 - A 'wad of cash' must consist of more than 20 (about) bills, of any denomination and can be folded, rolled, crumbled, etc.",
    "WARNING": "160 - A warning issued by the officer is a statement that the motorist has committed some offense, but is being spared the actual citation.",
    "WARRANT": "161 - The courts can issue a warrant authorizing the police to arrest.",
    "WEED FOUND": "162 - Cannabis also known as marijuana among several other names, found in vehicle or on a person or in belongings.",
    "WEED PIPE": "163 - Pipe or any other instrument in which the marijuana is placed (packed) to be smoked.",
    "WELFARE CHECK": "164 - A police welfare check occurs when a report is made to law enforcement about an individual who may be in some sort of peril, usually in that person's residence.",
    "WILD ANIMAL": "165 - An animal living in a state of nature; not tamed or domesticated.",
    "MIRANDA RIGHTS": "You have the right to remain silent and refuse to answer questions; Anything you say may be used against you in a court of law; You have the right to consult an attorney before speaking to the police and to have an attorney present during questioning now or in the future.; If you cannot afford an attorney, one will be appointed for you before any questioning if you wish.; If you decide to answer questions now without an attorney present, you will still have the right to stop answering at any time until you talk to an attorney.; Knowing and understanding your rights as I have explained them to you, are you willing to answer my questions without an attorney present?"
}

CONVERT = {
    "'COPASTETIC'": "'Copastetic",
    "'PORN' AGAIN": "'Porn' Again",
    "ACCIDENT": "Accident",
    "ACTIN' A FOOL": "Actin' A Fool",
    "ALCOHOL": "Alcohol",
    "AMBULANCE": "Ambulance",
    "AMMUNITION": "Ammunition",
    "ANKLE BRACELET": "Ankle Bracelet",
    "ARMED ROBBERY": "Armed Robbery",
    "ARRESTED": "Arrested",
    "ASSAULT": "Assault",
    "ASSAULT RIFLE": "Assault Rifle",
    "BAREFOOT": "Barefoot",
    "BARKING DOG": "Barking Dog",
    "BEER": "Beer",
    "BEER GUT": "Beer Gut",
    "BICYCLE": "Bicycle",
    "BLOOD": "Blood",
    "BLUE DOOR MOTEL": "Blue Door Motel",
    "BLUNT": "Blunt",
    "BODILY FLUIDS": "Bodily Fluids",
    "BRASS KNUCKLES": "Brass Knuckles",
    "BREATHALYZER": "Breathalyzer",
    "BRICK O' WEED": "Brick O' Weed",
    "BROKEN HEADLIGHT": "Broken Headlight",
    "BROKEN TAILLIGHT": "Broken Taillight",
    "BURGLARY": "Burglary",
    "CSI": "CSI",
    "CAMOUFLAGE": "Camouflage",
    "CAR CHASE": "Car Chase",
    "CAR SEAT": "Car Seat",
    "CHILD NEGLECT": "Child Neglect",
    "CIGARETTE": "Cigarette",
    "CLENCHED BUTTOCKS": "Clenched Buttocks",
    "COCAINE": "Cocaine",
    "CONSTTIUTIONALIST": "Constitutionalist",
    "CONVICT": "Convict",
    "COP TAKE DOWN": "Cop Take Down",
    "COUGH SYRUP": "Cough Syrup",
    "CROWN ROYAL BAG": "Crown Royal Bag",
    "CRYING": "Crying",
    "CYCLING DIRTY": "Cycling Dirty",
    "DUI CHECKPOINT": "DUI Checkpoint",
    "DUI TEST": "DUI Test",
    "DAISY DUKES": "Daisy Dukes",
    "DAN ABRAMS IS 'PUN'NY": "Dan Abrams is 'Pun'ny",
    "DESTROYING EVIDENCE": "Destroying Evidence",
    "DETAINED": "Detained",
    "DOG BITE": "Dog Bite",
    "DOMESTIC ANIMAL": "Domestic Animal",
    "DOMESTIC DISTURBANCE": "Domestic Disturbance",
    "DON'T FILM ME": "Don't Film Me",
    "DRUG BUST": "Drug Bust",
    "DRUG PARAPHERNALIA": "Drug Paraphernalia",
    "DRUGS TOSSED": "Drugs Tossed",
    "DRUNK WALKING": "Drunk Walking",
    "EXPIRED LICENSE": "Expired License",
    "EXPIRED TAGS": "Expired Tags",
    "FAKE ID": "Fake ID",
    "FARM ANIMAL": "Farm Animal",
    "FIGHT": "Fight",
    "FIRE": "Fire",
    "FIST BUMP": "Fist Bump",
    "FIVE FINGER DISCOUNT": "Five Finger Discount",
    "FOOT CHASE": "Foot Chase",
    "FREQUENT-FLYER": "Frequent-Flyer",
    "FULL MOON": "Full Moon",
    "GANG BANGER": "Gang Banger",
    "GANG UNIT": "Gang Unit",
    "GIFTIE": "Giftie",
    "GOOBER GRAZING": "Goober Grazing",
    "GOOD SAMARITAN": "Good Samaritan",
    "GRILLING": "Grilling",
    "GUN FOUND": "Gun Found",
    "GUN SHOW": "Gun Show",
    "HANDCUFFED": "Handcuffed",
    "HANDGUN": "Handgun",
    "HANDSHAKE": "Handshake",
    "HELICOPTER": "Helicopter",
    "HIT & RUN": "Hit & Run",
    "HOGTIED": "Hogtied",
    "HOOKER": "Hooker",
    "HOOPTY": "Hoopty",
    "JAWS OF LIFE": "Jaws of Life",
    "K9 USED": "K9 Used",
    "KITTY CAT": "Kitty Cat",
    "KNIFE": "Knife",
    "LATEX GLOVES": "Latex Gloves",
    "LIAR, LIAR": "Liar, Liar",
    "LIGHTS OFF": "Lights Off",
    "LITTERING": "Littering",
    "LIVEPD NATLIE": "LivePD Natlie",
    "LIVEPD SHOUTOUT": "LivePD Shoutout",
    "LIVEPD IS FOR LOVERS": "LivePD is for Lovers",
    "MAN BUN": "Man Bun",
    "METH": "Meth",
    "METH PIPE": "Meth Pipe",
    "MOOBS": "Moobs",
    "MOTORCYCLE CHASE": "Motorcycle Chase",
    "MOUTH SALAD": "Mouth Salad",
    "NARCAN": "Narcan",
    "NEEDLE": "Needle",
    "NIGHT VISION": "Night Vision",
    "NO HEADLIGHTS": "No Headlights",
    "NO ID": "No ID",
    "NO INSURANCE": "No Insurance",
    "NO PANTS": "No Pants",
    "NO SEAT BELT": "No Seat Belt",
    "NO SHOES": "No Shoes",
    "NOISE COMPLAINT": "Noise Complaint",
    "NOT MY...": "Not My...",
    "OBAMA MART": "Obama Mart",
    "OPEN CONTAINER": "Open Container",
    "OUT OF STATE LICENSE": "Out of State License",
    "PCP": "PCP",
    "PILLS": "Pills",
    "PINK HANDCUFFS": "Pink Handcuffs",
    "PRISON PURSE": "Prison Purse",
    "PROBATION": "Probation",
    "RESISTING ARREST": "Resisting Arrest",
    "RESTRICTED LICENSE": "Restricted License",
    "RIDIN' DIRTY": "Ridin' Dirty",
    "RIDIN' DIRTY TRIFECTA": "Ridin' Dirty Trifecta",
    "RIGHTS READ": "Rights Read",
    "ROAD RAGE": "Road Rage",
    "SWAT": "SWAT",
    "SAGGING PANTS": "Sagging Pants",
    "SCALES": "Scales",
    "SEARCH": "Search",
    "SELFIE": "Selfie",
    "SEX IN CAR": "Sex in Car",
    "SEX OFFENDER": "Sex Offender",
    "SEX TOY": "Sex Toy",
    "SHOTGUN": "Shotgun",
    "SHOTS FIRED": "Shots Fired",
    "SNAKE": "Snake",
    "SOCKS 'N SLIDES": "Socks 'n Slides",
    "SPIKE STRIP": "Spike Strip",
    "SPIT HOOD": "Spit Hood",
    "SPITTING": "Spitting",
    "SPOON": "Spoon",
    "STICKS": "Sticks",
    "STOLEN CAR": "Stolen Car",
    "STOLEN TAGS": "Stolen Tags",
    "SUSPENDED LICENSE": "Suspended License",
    "SUSPICIOUS VEHICLE": "Suspicious Vehicle",
    "TAG LIGHT": "Tag Light",
    "TASER": "Taser",
    "TATTOOS": "Tattoos",
    "TEAM RCSD": "Team RCSD",
    "THANK YOU": "Thank You",
    "TINT VIOLATION": "Tint Violation",
    "TOOTERS": "Tooters",
    "TOUCH TAIL LIGHT": "Touch Tail Light",
    "TRAFFIC STOP": "Traffic Stop",
    "TRESPASSING": "Trespassing",
    "TWEAKER": "Tweaker",
    "UNDERAGE DRINKING": "Underage Drinking",
    "WAD OF CASH": "Wad of Cash",
    "WARNING": "Warning",
    "WARRANT": "Warrant",
    "WEED FOUND": "Weed Found",
    "WEED PIPE": "Weed Pipe",
    "WELFARE CHECK": "Welfare Check",
    "WILD ANIMAL": "Wild Animal",
}